[[factors]]
group="temp"
factorNames= [
                "r2dt",
                "fet",
                "fdt",
                "ct",
                "speed7"
            ]


[[factors]]
group="shape"
factorNames= [
                "thick_clg",
                "crown40",
                "wedge40",
                "sym_flt",
                "asym_flt",
                "r2_center_ofs",
                "fm_center_ofs"
            ]


[[factors]]
group="calc_length"
factorNames= [
                "clg_calc_length",
                "mfg_calc_length",
                "calc_length1",
                "calc_length2",
                "calc_length3",
                "calc_length4",
                "calc_length5",
                "calc_length6",
                "calc_length7",
                "fm_calc_length",
                "flt_calc_length",
                "r2dt_calc_length",
                "r2dw_calc_length",
                "ct_calc_length",
                "fet_calc_length",
                "fdt_calc_length"
            ]

[[factors]]
group="fm_stand"
factorNames= [
                "looper_angle",
                "total_rolling_force",
                "diff_rolling_force",
                "ct_gap",
                "os_bend_force",
                "ds_bend_force",
                "leveling",
            ]
